import type { CarListing } from "@/types"

export const MOCK_SHOP_LISTINGS: CarListing[] = [
  {
    id: "1",
    title: "2018 Hyundai County 29-Seater Bus",
    year: 2018,
    make: "Hyundai",
    model: "County",
    trim: "29-Seater Long Body",
    price: 35000,
    currency: "USD",
    location: "Busan, South Korea",
    images: ["/hyundai-county-bus-white-commercial.jpg"],
    transmission: "Manual",
    fuelType: "Diesel",
    mileage: 120000,
    mileageUnit: "km",
    isReserved: false,
    verified: true,
    dealerId: "dealer-2",
    seller: {
      name: "Busan Commercial Vehicles",
      rating: 4.9,
      totalReviews: 156,
    },
    sellerRating: 4.9,
    sellerTotalReviews: 156,
    isFavorite: false,
    showTranslate: false,
    bodyType: "Bus",
    destinationPorts: ["Lagos", "Tema Port", "Mombasa", "Conakry"],
    features: ["29 Seats", "Air Conditioning", "Power Steering", "ABS Brakes"],
    description: "Well-maintained commercial bus perfect for public transport. Ready for immediate export.",
  },
  {
    id: "2",
    title: "2020 Kia K5 GT-Line",
    year: 2020,
    make: "Kia",
    model: "K5",
    trim: "GT-Line Turbo",
    price: 28500,
    currency: "USD",
    location: "Seoul, South Korea",
    images: ["/kia-k5-gt-line-sedan-red.jpg"],
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: 45000,
    mileageUnit: "km",
    isReserved: false,
    verified: true,
    dealerId: "dealer-1",
    seller: {
      name: "Seoul Premium Motors",
      rating: 4.8,
      totalReviews: 203,
    },
    sellerRating: 4.8,
    sellerTotalReviews: 203,
    isFavorite: true,
    showTranslate: false,
    bodyType: "Sedan",
    destinationPorts: ["Lagos", "Tema Port", "Mombasa"],
    features: ["Turbo Engine", "Leather Seats", "Sunroof", "Navigation"],
    description: "Sporty sedan with premium features and excellent fuel economy.",
  },
  {
    id: "3",
    title: "2019 Genesis G70 Sport",
    year: 2019,
    make: "Genesis",
    model: "G70",
    trim: "2.0T Sport",
    price: 32000,
    originalPrice: 35000,
    currency: "USD",
    location: "Incheon, South Korea",
    images: ["/genesis-g70-luxury-sedan-silver.jpg"],
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: 38000,
    mileageUnit: "km",
    isReserved: false,
    verified: true,
    dealerId: "dealer-3",
    seller: {
      name: "Incheon Luxury Auto",
      rating: 4.9,
      totalReviews: 127,
    },
    sellerRating: 4.9,
    sellerTotalReviews: 127,
    isFavorite: false,
    showTranslate: false,
    bodyType: "Sedan",
    destinationPorts: ["Lagos", "Mombasa"],
    features: ["Sport Package", "Premium Audio", "Heated Seats", "Adaptive Cruise"],
    description: "Luxury sport sedan with cutting-edge technology and performance.",
  },
  {
    id: "4",
    title: "2021 Hyundai Tucson Hybrid",
    year: 2021,
    make: "Hyundai",
    model: "Tucson",
    trim: "Hybrid Premium",
    price: 29000,
    currency: "USD",
    location: "Daegu, South Korea",
    images: ["/hyundai-tucson-hybrid-suv-blue.jpg"],
    transmission: "Automatic",
    fuelType: "Hybrid",
    mileage: 32000,
    mileageUnit: "km",
    isReserved: false,
    verified: true,
    dealerId: "dealer-4",
    seller: {
      name: "Daegu Eco Motors",
      rating: 4.7,
      totalReviews: 89,
    },
    sellerRating: 4.7,
    sellerTotalReviews: 89,
    isFavorite: false,
    showTranslate: false,
    bodyType: "SUV",
    destinationPorts: ["Tema Port", "Lagos", "Mombasa"],
    features: ["Hybrid Engine", "Smart Cruise", "360 Camera", "Wireless Charging"],
    description: "Efficient hybrid SUV perfect for urban and highway driving.",
  },
  {
    id: "5",
    title: "2022 Kia EV6 GT-Line AWD",
    year: 2022,
    make: "Kia",
    model: "EV6",
    trim: "GT-Line AWD",
    price: 48000,
    currency: "USD",
    location: "Seoul, South Korea",
    images: ["/kia-ev6-electric-suv-white.jpg"],
    transmission: "Automatic",
    fuelType: "Electric",
    mileage: 18000,
    mileageUnit: "km",
    isReserved: false,
    verified: true,
    dealerId: "dealer-5",
    seller: {
      name: "Seoul EV Center",
      rating: 5.0,
      totalReviews: 94,
    },
    sellerRating: 5.0,
    sellerTotalReviews: 94,
    isFavorite: true,
    showTranslate: false,
    bodyType: "SUV",
    destinationPorts: ["Lagos", "Mombasa"],
    features: ["AWD", "Fast Charging", "Premium Interior", "Advanced Safety"],
    description: "Award-winning electric SUV with impressive range and technology.",
  },
  {
    id: "6",
    title: "2017 Hyundai Grand Starex Van",
    year: 2017,
    make: "Hyundai",
    model: "Grand Starex",
    trim: "12-Seater Van",
    price: 22000,
    currency: "USD",
    location: "Busan, South Korea",
    images: ["/hyundai-grand-starex-van-silver.jpg"],
    transmission: "Manual",
    fuelType: "Diesel",
    mileage: 150000,
    mileageUnit: "km",
    isReserved: false,
    verified: false,
    dealerId: "dealer-6",
    seller: {
      name: "Busan Van Sales",
      rating: 4.5,
      totalReviews: 67,
    },
    sellerRating: 4.5,
    sellerTotalReviews: 67,
    isFavorite: false,
    showTranslate: false,
    bodyType: "Van",
    destinationPorts: ["Tema Port", "Lagos", "Conakry"],
    features: ["12 Seats", "Diesel Engine", "Spacious Interior", "Reliable"],
    description: "Practical van for passenger transport with proven reliability.",
  },
  {
    id: "7",
    title: "2020 Kia Sorento SX",
    year: 2020,
    make: "Kia",
    model: "Sorento",
    trim: "SX Prestige",
    price: 31500,
    currency: "USD",
    location: "Seoul, South Korea",
    images: ["/kia-sorento-suv-black.jpg"],
    transmission: "Automatic",
    fuelType: "Diesel",
    mileage: 55000,
    mileageUnit: "km",
    isReserved: false,
    verified: true,
    dealerId: "dealer-7",
    seller: {
      name: "Seoul Motors",
      rating: 4.8,
      totalReviews: 178,
    },
    sellerRating: 4.8,
    sellerTotalReviews: 178,
    isFavorite: false,
    showTranslate: false,
    bodyType: "SUV",
    destinationPorts: ["Lagos", "Tema Port", "Mombasa"],
    features: ["7 Seats", "Leather", "Panoramic Roof", "Smart Features"],
    description: "Premium 7-seater SUV perfect for families.",
  },
  {
    id: "8",
    title: "2019 Genesis GV80",
    year: 2019,
    make: "Genesis",
    model: "GV80",
    trim: "3.0T AWD",
    price: 42000,
    currency: "USD",
    location: "Seoul, South Korea",
    images: ["/genesis-gv80-luxury-suv-black.jpg"],
    transmission: "Automatic",
    fuelType: "Petrol",
    mileage: 42000,
    mileageUnit: "km",
    isReserved: false,
    verified: true,
    dealerId: "dealer-1",
    seller: {
      name: "Seoul Premium Motors",
      rating: 4.8,
      totalReviews: 203,
    },
    sellerRating: 4.8,
    sellerTotalReviews: 203,
    isFavorite: false,
    showTranslate: false,
    bodyType: "SUV",
    destinationPorts: ["Lagos", "Mombasa"],
    features: ["AWD", "Luxury Interior", "Advanced Safety", "Premium Sound"],
    description: "Flagship luxury SUV with exceptional comfort and technology.",
  },
]

export const SHOP_COUNTRY_PRESETS = [
  { id: "gh", name: "Ghana", port: "Tema Port", flag: "🇬🇭" },
  { id: "ng", name: "Nigeria", port: "Lagos", flag: "🇳🇬" },
  { id: "ke", name: "Kenya", port: "Mombasa", flag: "🇰🇪" },
  { id: "gn", name: "Guinea", port: "Conakry", flag: "🇬🇳" },
]

export const AFRICAN_PORTS = [
  { id: "tema", name: "Tema Port", country: "Ghana", code: "GH" },
  { id: "lagos", name: "Lagos", country: "Nigeria", code: "NG" },
  { id: "mombasa", name: "Mombasa", country: "Kenya", code: "KE" },
  { id: "conakry", name: "Conakry", country: "Guinea", code: "GN" },
  { id: "durban", name: "Durban", country: "South Africa", code: "ZA" },
  { id: "daressalaam", name: "Dar es Salaam", country: "Tanzania", code: "TZ" },
]
