export type PartSegment = "new" | "used" | "machine"

export interface Part {
    id: string
    name: string
    partNumber: string
    brand: string // Manufacturer (e.g., Mobis, Bosch, Genuine)
    category: string
    subcategory: string
    segment: PartSegment // New field for top-level segmentation
    description: string
    priceKRW: number
    priceUSD: number
    compatibleVehicles: string[]
    condition: "New" | "Used" | "Refurbished" | "Remanufactured"
    stockStatus: "In Stock" | "Low Stock" | "Out of Stock"
    images: string[]
    rating: number
    reviewCount: number
    location?: string // Useful for used parts (e.g., "Incheon Yard 3")
}

export interface CategoryGroup {
    id: string
    name: string
    subcategories: string[]
}

// 1. CAR PARTS (Shared categories for New & Used, but maybe used has distinct ones like 'Half Cuts')
export const CAR_PARTS_CATEGORIES: CategoryGroup[] = [
    {
        id: "engine",
        name: "Engine & Drivetrain",
        subcategories: ["Complete Engines", "Transmission Assembly", "Turbochargers", "Fuel Injectors", "Filters", "Belts & Pulleys"],
    },
    {
        id: "body",
        name: "Exterior & Body",
        subcategories: ["Bumpers", "Doors", "Hoods", "Headlights", "Taillights", "Mirrors", "Grilles", "Nose Cuts"],
    },
    {
        id: "suspension",
        name: "Suspension & Steering",
        subcategories: ["Shock Absorbers", "Control Arms", "Steering Racks", "Hub Bearings", "Axles"],
    },
    {
        id: "electrical",
        name: "Electrical & Lighting",
        subcategories: ["ECU/ECM", "Alternators", "Starters", "Instrument Clusters", "Wiring Harnesses"],
    },
    {
        id: "interior",
        name: "Interior & Trim",
        subcategories: ["Seats", "Door Panels", "Dashboard Components", "Steering Wheels", "Airbags"],
    },
    {
        id: "general",
        name: "General Parts",
        subcategories: ["Miscellaneous", "Accessories", "Consumables"],
    },
]

// 2. HEAVY MACHINE PARTS (Distinct categories)
export const MACHINE_PARTS_CATEGORIES: CategoryGroup[] = [
    {
        id: "hydraulics",
        name: "Hydraulic System",
        subcategories: ["Main Pumps", "Travel Motors", "Swing Motors", "Control Valves", "Cylinders (Boom/Arm/Bucket)"],
    },
    {
        id: "undercarriage",
        name: "Undercarriage",
        subcategories: ["Track Chains", "Rollers", "Idlers", "Sprockets", "Track Shoes"],
    },
    {
        id: "bearings",
        name: "Bearings & Seals",
        subcategories: ["Bearings", "Seal Kits", "Gaskets"],
    },
    {
        id: "engine_heavy",
        name: "Heavy Engine Parts",
        subcategories: ["Piston/Liner Kits", "Crankshafts", "Camshafts", "Injectors", "Turbochargers"],
    },
    {
        id: "attachments",
        name: "Attachments",
        subcategories: ["Buckets", "Breakers", "Grapples", "Quick Couplers"],
    },
]

export const MOCK_PARTS: Part[] = [
    // --- NEW PARTS ---
    {
        id: "n1",
        name: "Genuine Oil Filter Kit (Bulk 10ea)",
        partNumber: "26300-35504-10",
        brand: "Mobis (Genuine)",
        category: "Engine & Drivetrain",
        subcategory: "Filters",
        segment: "new",
        description: "Original Hyundai/Kia oil filter. Box of 10. Essential for regular maintenance.",
        priceKRW: 55000,
        priceUSD: 42.00,
        compatibleVehicles: ["Hyundai Sonata", "Kia Optima", "Hyundai Tucson"],
        condition: "New",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 5.0,
        reviewCount: 45,
    },
    {
        id: "n2",
        name: "Front Brake Pad Set (Ceramic)",
        partNumber: "58101-3QA10",
        brand: "Sangsin Hi-Q",
        category: "Suspension & Steering",
        subcategory: "Brake Pads", // Mapped loosely to suspension/chassis context or add specific brake cat
        segment: "new",
        description: "High-performance ceramic pads. Low dust, low noise.",
        priceKRW: 35000,
        priceUSD: 26.00,
        compatibleVehicles: ["Hyundai Sonata YF", "Kia K5"],
        condition: "New",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 4.8,
        reviewCount: 120,
    },

    // --- USED PARTS (Specific Items) ---
    {
        id: "u1",
        name: "Used Engine Assembly - Hyundai Theta II 2.4L",
        partNumber: "G4KJ-Assy",
        brand: "Hyundai (Genuine)",
        category: "Engine & Drivetrain",
        subcategory: "Complete Engines",
        segment: "used",
        description: "Tested good running engine. Compression tested. 85,000km mileage. Includes intake manifold.",
        priceKRW: 1200000,
        priceUSD: 900.00,
        compatibleVehicles: ["Hyundai Sonata YF", "Kia Sportage R"],
        condition: "Used",
        stockStatus: "In Stock",
        location: "Incheon Dismantling Yard 2",
        images: ["/placeholder-part.jpg"],
        rating: 0,
        reviewCount: 0,
    },
    {
        id: "u2",
        name: "Headlight Assembly (Left) - LED Type",
        partNumber: "92101-C1000",
        brand: "Mobis (Genuine)",
        category: "Exterior & Body",
        subcategory: "Headlights",
        segment: "used",
        description: "Clean lens, no cracks. One mounting tab repaired (solid). Fully functional.",
        priceKRW: 150000,
        priceUSD: 112.00,
        compatibleVehicles: ["Hyundai Sonata LF"],
        condition: "Used",
        stockStatus: "In Stock",
        location: "Busan Warehouse",
        images: ["/placeholder-part.jpg"],
        rating: 0,
        reviewCount: 0,
    },
    {
        id: "u3",
        name: "Nose Cut (Front Clip) - Kia K5 2015",
        partNumber: "NC-K5-2015-WHT",
        brand: "Kia",
        category: "Exterior & Body",
        subcategory: "Nose Cuts",
        segment: "used",
        description: "Complete front cut including bumper, headlights, radiator support, and coolers. Color: Snow White Pearl.",
        priceKRW: 850000,
        priceUSD: 640.00,
        compatibleVehicles: ["Kia K5 (Optima) 2014-2016"],
        condition: "Used",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 0,
        reviewCount: 0,
    },

    // --- MORE NEW PARTS ---
    {
        id: "n3",
        name: "LED Headlight Assembly (Left) - Full LED",
        partNumber: "92101-S8100",
        brand: "Mobis (Genuine)",
        category: "Exterior & Body",
        subcategory: "Headlights",
        segment: "new",
        description: "Original Hyundai full LED headlight. Includes DRL and turn signal modules.",
        priceKRW: 450000,
        priceUSD: 338.00,
        compatibleVehicles: ["Hyundai Palisade 2020-2024"],
        condition: "New",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 4.9,
        reviewCount: 23,
    },
    {
        id: "n4",
        name: "Timing Chain Kit Complete",
        partNumber: "24321-2G100",
        brand: "Mobis (Genuine)",
        category: "Engine & Drivetrain",
        subcategory: "Belts & Pulleys",
        segment: "new",
        description: "Complete timing chain kit with tensioners, guides, and chains. OEM quality.",
        priceKRW: 185000,
        priceUSD: 139.00,
        compatibleVehicles: ["Hyundai Sonata", "Kia Optima", "Hyundai Santa Fe"],
        condition: "New",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 4.7,
        reviewCount: 67,
    },
    {
        id: "n5",
        name: "Front Shock Absorber Set (Pair)",
        partNumber: "54651-C1050",
        brand: "Mando (OEM Supplier)",
        category: "Suspension & Steering",
        subcategory: "Shock Absorbers",
        segment: "new",
        description: "Premium gas-filled shock absorbers. Sold as pair for front axle.",
        priceKRW: 220000,
        priceUSD: 165.00,
        compatibleVehicles: ["Hyundai Sonata DN8", "Kia K5"],
        condition: "New",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 4.8,
        reviewCount: 34,
    },
    {
        id: "n6",
        name: "ECU Engine Control Module",
        partNumber: "39110-2G661",
        brand: "Kefico (Genuine)",
        category: "Electrical & Lighting",
        subcategory: "ECU/ECM",
        segment: "new",
        description: "Brand new ECU. Requires VIN programming at dealer.",
        priceKRW: 680000,
        priceUSD: 510.00,
        compatibleVehicles: ["Hyundai Sonata YF 2.4L"],
        condition: "New",
        stockStatus: "Low Stock",
        images: ["/placeholder-part.jpg"],
        rating: 5.0,
        reviewCount: 12,
    },

    // --- MORE USED PARTS ---
    {
        id: "u4",
        name: "Automatic Transmission Assembly - A6MF1",
        partNumber: "45000-3B250",
        brand: "Hyundai (Genuine)",
        category: "Engine & Drivetrain",
        subcategory: "Transmission Assembly",
        segment: "used",
        description: "Tested working 6-speed automatic. 72,000km. Clean fluid, no slipping.",
        priceKRW: 950000,
        priceUSD: 712.00,
        compatibleVehicles: ["Hyundai Sonata YF", "Kia K5"],
        condition: "Used",
        stockStatus: "In Stock",
        location: "Seoul Dismantling Center",
        images: ["/placeholder-part.jpg"],
        rating: 0,
        reviewCount: 0,
    },
    {
        id: "u5",
        name: "Complete Door Assembly (Front Right)",
        partNumber: "76004-C1000",
        brand: "Hyundai",
        category: "Exterior & Body",
        subcategory: "Doors",
        segment: "used",
        description: "Complete door with glass, regulator, and trim. Color: Phantom Black. Minor scratches.",
        priceKRW: 280000,
        priceUSD: 210.00,
        compatibleVehicles: ["Hyundai Sonata DN8 2020-2024"],
        condition: "Used",
        stockStatus: "In Stock",
        location: "Busan Auto Recycling",
        images: ["/placeholder-part.jpg"],
        rating: 0,
        reviewCount: 0,
    },
    {
        id: "u6",
        name: "Leather Seat Set (Front + Rear)",
        partNumber: "INT-SEAT-SET",
        brand: "Kia",
        category: "Interior & Trim",
        subcategory: "Seats",
        segment: "used",
        description: "Black leather heated seats. Driver seat has minor wear. Includes all brackets.",
        priceKRW: 650000,
        priceUSD: 488.00,
        compatibleVehicles: ["Kia K5 2016-2020"],
        condition: "Used",
        stockStatus: "In Stock",
        location: "Incheon Parts Yard",
        images: ["/placeholder-part.jpg"],
        rating: 0,
        reviewCount: 0,
    },

    // --- MACHINE PARTS ---
    {
        id: "m1",
        name: "Hydraulic Main Pump K3V112",
        partNumber: "31H6-00010",
        brand: "Kawasaki (OEM for Hyundai)",
        category: "Hydraulic System",
        subcategory: "Main Pumps",
        segment: "machine",
        description: "Rebuilt Kawasaki K3V112DT pump. Fits Hyundai R210LC-7 Excavator. Warranty 6 months.",
        priceKRW: 2500000,
        priceUSD: 1880.00,
        compatibleVehicles: ["Hyundai R210LC-7", "Doosan DX225"],
        condition: "Remanufactured",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 5.0,
        reviewCount: 3,
    },
    {
        id: "m2",
        name: "Track Group (Link Assy) - 49 Links",
        partNumber: "145-23456",
        brand: "DCF (Aftermarket)",
        category: "Undercarriage",
        subcategory: "Track Chains",
        segment: "machine",
        description: "Heavy duty sealed and lubricated track chain. Fits 20-ton class excavators.",
        priceKRW: 1800000,
        priceUSD: 1350.00,
        compatibleVehicles: ["Doosan DX220", "Volvo EC210", "Hyundai R210"],
        condition: "New",
        stockStatus: "Low Stock",
        images: ["/placeholder-part.jpg"],
        rating: 4.5,
        reviewCount: 8,
    },
    {
        id: "m3",
        name: "Swing Motor Assembly",
        partNumber: "31N6-10160",
        brand: "Hyundai (Genuine)",
        category: "Hydraulic System",
        subcategory: "Swing Motors",
        segment: "machine",
        description: "New genuine swing motor. Direct replacement for R210LC-7 series.",
        priceKRW: 3200000,
        priceUSD: 2400.00,
        compatibleVehicles: ["Hyundai R210LC-7", "Hyundai R210LC-9"],
        condition: "New",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 5.0,
        reviewCount: 5,
    },
    {
        id: "m4",
        name: "Excavator Bucket 0.8m³",
        partNumber: "61N6-31320",
        brand: "Hyundai",
        category: "Attachments",
        subcategory: "Buckets",
        segment: "machine",
        description: "Standard digging bucket with teeth. Fits 20-ton class excavators.",
        priceKRW: 1500000,
        priceUSD: 1125.00,
        compatibleVehicles: ["Hyundai R210", "Doosan DX225", "Volvo EC210"],
        condition: "New",
        stockStatus: "In Stock",
        images: ["/placeholder-part.jpg"],
        rating: 4.6,
        reviewCount: 11,
    },
]
